# Generated by Django 5.0.7 on 2026-09-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requeststatushistory',
            options={'ordering': ['timestamp', 'id'], 'verbose_name': 'Status History Entry', 'verbose_name_plural': 'Status History'},
        ),
    ]
