# Generated by Django 5.0.7 on 2026-09-19 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the CA service.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed scope and details of the service.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Service fee in INR.', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this service is currently visible to clients.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/description of document required (e.g. PAN Card, Form 16, Bank Statement).', max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='catalog.service')),
            ],
            options={
                'verbose_name': 'Document Requirement',
                'verbose_name_plural': 'Document Requirements',
                'ordering': ['id'],
            },
        ),
    ]
